owner: JaswanthRemiel # GitHub username
repo: uptime # GitHub repository name
sites: # List of endpoints to track
  - name: portfolio
    url: https://remiel.fyi
  - name: LinkDescri-AI
    url: https://tools.remiel.fyi/
assignees: # Users to assign downtime issues (optional)
  - JaswanthRemiel
status-website:
  # baseUrl: /uptime
  cname: uptime.remiel.fyi
  name: Uptime status
  
