owner: JaswanthRemiel 
repo: uptime 
sites:
  - name: Portfolio
    url: https://remiel.fyi
  - name: Tools
    url: https://tools.remiel.fyi/
  - name: Blog
    url: https://remiel.fyi/blog
assignees: 
  - JaswanthRemiel
status-website:
  cname: uptime.remiel.fyi
  name: Uptime status
  
