owner: JaswanthRemiel # GitHub username
repo: uptime # GitHub repository name
sites: # List of endpoints to track
  - name: portfolio
    url: https://www.remiel.fyi
assignees: # Users to assign downtime issues (optional)
  - JaswanthRemiel
status-website:
  baseUrl: /uptime
  # where "repo" is your repository name
  # cname: uptime.remiel.fyi
  name: Uptime status
